name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0
      - run: npm ci
      - run: npm run build
      - run: npx jest --maxWorkers 2
        env:
          CI: true
